# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lec9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lec9
pod 'SDWebImage'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
